name: Hello World  
on: [push,pull_request]
  #workflow_dispatch:

jobs:  
  greet:  
    runs-on: ubuntu-latest  
    
    # tie this job to your QA-ENV environment
    
    environment: QA-ENV
    steps:  
      - run: echo "Hello, GitHub Actions!"
      - run: echo "${{ vars.PRINT_VAR }}"
